SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `BP_Lovacki_Savez` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `BP_Lovacki_Savez` ;

CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`OSOBA` (
  `JMB` VARCHAR(13) NOT NULL,
  `BrojLicneKarte` VARCHAR(9) NOT NULL,
  `Prezime` VARCHAR(50) NOT NULL,
  `Ime` VARCHAR(50) NOT NULL,
  `Adresa` VARCHAR(80) NOT NULL,
  `Telefon` VARCHAR(45) NOT NULL,
  `OsobaId` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `JMB_UNIQUE` (`JMB` ASC) VISIBLE,
  PRIMARY KEY (`OsobaId`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`KALIBAR_ORUZJA` (
  `KalibarOruzjaId` INT NOT NULL AUTO_INCREMENT,
  `Kalibar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`KalibarOruzjaId`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`VRSTA_ORUZJA` (
  `VrstaOruzjaId` INT NOT NULL AUTO_INCREMENT,
  `VrstaOruzjaNaziv` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`VrstaOruzjaId`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`MARKA_ORUZJA` (
  `MarkaOruzjaId` INT NOT NULL AUTO_INCREMENT,
  `MarkaOruzjaNaziv` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`MarkaOruzjaId`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`ORUZJE` (
  `FabrickiBroj` VARCHAR(5) NOT NULL,
  `VrstaOruzjaId` INT NOT NULL,
  `MarkaOruzjaId` INT NOT NULL,
  `KalibarOruzjaId` INT NOT NULL,
  PRIMARY KEY (`FabrickiBroj`, `VrstaOruzjaId`, `MarkaOruzjaId`, `KalibarOruzjaId`),
  UNIQUE INDEX `FabrickiBroj_UNIQUE` (`FabrickiBroj` ASC) VISIBLE,
  INDEX `fk_ORUZJE_KALIBAR_ORUZJA1_idx` (`KalibarOruzjaId` ASC) VISIBLE,
  INDEX `fk_ORUZJE_VRSTA_ORUZJA1_idx` (`VrstaOruzjaId` ASC) VISIBLE,
  INDEX `fk_ORUZJE_MARKA_ORUZJA1_idx` (`MarkaOruzjaId` ASC) VISIBLE,
  CONSTRAINT `fk_ORUZJE_KALIBAR_ORUZJA1`
    FOREIGN KEY (`KalibarOruzjaId`)
    REFERENCES `BP_Lovacki_Savez`.`KALIBAR_ORUZJA` (`KalibarOruzjaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ORUZJE_VRSTA_ORUZJA1`
    FOREIGN KEY (`VrstaOruzjaId`)
    REFERENCES `BP_Lovacki_Savez`.`VRSTA_ORUZJA` (`VrstaOruzjaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ORUZJE_MARKA_ORUZJA1`
    FOREIGN KEY (`MarkaOruzjaId`)
    REFERENCES `BP_Lovacki_Savez`.`MARKA_ORUZJA` (`MarkaOruzjaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`ADMINISTRATOR` (
  `KorisnickoIme` VARCHAR(50) NOT NULL,
  `Lozinka` VARCHAR(500) NOT NULL,
  `OsobaId` INT NOT NULL,
  PRIMARY KEY (`OsobaId`),
  UNIQUE INDEX `KorisnickoIme_UNIQUE` (`KorisnickoIme` ASC) VISIBLE,
  CONSTRAINT `fk_ADMINISTRATOR_OSOBA1`
    FOREIGN KEY (`OsobaId`)
    REFERENCES `BP_Lovacki_Savez`.`OSOBA` (`OsobaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`MJESTO` (
  `BrojPoste` VARCHAR(10) NOT NULL,
  `Naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BrojPoste`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`LOVACKI_SAVEZ` (
  `LovackiSavezId` INT NOT NULL AUTO_INCREMENT,
  `LovackiSavezNaziv` VARCHAR(45) NOT NULL,
  `LovackiSavezAdresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LovackiSavezId`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`LOVACKO_UDRUZENJE` (
  `LovackoUdruzenjeId` INT NOT NULL AUTO_INCREMENT,
  `LovackoUdruzenjeNaziv` VARCHAR(45) NOT NULL,
  `BrojPoste` VARCHAR(10) NOT NULL,
  `LovackiSavezId` INT NOT NULL,
  PRIMARY KEY (`LovackoUdruzenjeId`),
  INDEX `fk_LOVACKO_UDRUZENJE_MJESTO1_idx` (`BrojPoste` ASC) VISIBLE,
  INDEX `fk_LOVACKO_UDRUZENJE_LOVACKI_SAVEZ1_idx` (`LovackiSavezId` ASC) VISIBLE,
  CONSTRAINT `fk_LOVACKO_UDRUZENJE_MJESTO1`
    FOREIGN KEY (`BrojPoste`)
    REFERENCES `BP_Lovacki_Savez`.`MJESTO` (`BrojPoste`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LOVACKO_UDRUZENJE_LOVACKI_SAVEZ1`
    FOREIGN KEY (`LovackiSavezId`)
    REFERENCES `BP_Lovacki_Savez`.`LOVACKI_SAVEZ` (`LovackiSavezId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`SEKCIJA` (
  `SekcijaId` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(50) NOT NULL,
  `BrojClanovaUSekciji` INT NOT NULL,
  `LovackoUdruzenjeId` INT NOT NULL,
  PRIMARY KEY (`SekcijaId`),
  INDEX `fk_SEKCIJA_LOVACKO_UDRUZENJE1_idx` (`LovackoUdruzenjeId` ASC) VISIBLE,
  CONSTRAINT `fk_SEKCIJA_LOVACKO_UDRUZENJE1`
    FOREIGN KEY (`LovackoUdruzenjeId`)
    REFERENCES `BP_Lovacki_Savez`.`LOVACKO_UDRUZENJE` (`LovackoUdruzenjeId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`CLAN` (
  `OsobaId` INT NOT NULL,
  `Status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`OsobaId`),
  CONSTRAINT `fk_CLAN_OSOBA1`
    FOREIGN KEY (`OsobaId`)
    REFERENCES `BP_Lovacki_Savez`.`OSOBA` (`OsobaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`CLANSKA_KARTA` (
  `ClanskaKartaId` INT NOT NULL AUTO_INCREMENT,
  `DatumUclanjivanja` DATE NOT NULL,
  `DatumIsclanjivanja` VARCHAR(10) NULL,
  `OsobaId` INT NOT NULL,
  PRIMARY KEY (`ClanskaKartaId`),
  INDEX `fk_CLANSKA_KARTA_CLAN1_idx` (`OsobaId` ASC) VISIBLE,
  CONSTRAINT `fk_CLANSKA_KARTA_CLAN1`
    FOREIGN KEY (`OsobaId`)
    REFERENCES `BP_Lovacki_Savez`.`CLAN` (`OsobaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`ORUZANI_LIST` (
  `SerijskiBroj` CHAR(6) NOT NULL,
  `DatumIzdavanja` DATE NOT NULL,
  `RokVazenja` VARCHAR(45) NOT NULL,
  `FabrickiBroj` VARCHAR(5) NOT NULL,
  `OsobaId` INT NOT NULL,
  PRIMARY KEY (`SerijskiBroj`),
  INDEX `fk_ORUZANI_LIST_ORUZJE1_idx` (`FabrickiBroj` ASC) VISIBLE,
  INDEX `fk_ORUZANI_LIST_CLAN1_idx` (`OsobaId` ASC) VISIBLE,
  CONSTRAINT `fk_ORUZANI_LIST_ORUZJE1`
    FOREIGN KEY (`FabrickiBroj`)
    REFERENCES `BP_Lovacki_Savez`.`ORUZJE` (`FabrickiBroj`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ORUZANI_LIST_CLAN1`
    FOREIGN KEY (`OsobaId`)
    REFERENCES `BP_Lovacki_Savez`.`CLAN` (`OsobaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`DIVLJAC` (
  `DivljacId` INT NOT NULL AUTO_INCREMENT,
  `Vrsta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DivljacId`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`LOVNI_KALENDAR` (
  `KalendarLovaId` INT NOT NULL AUTO_INCREMENT,
  `DatumPocetka` DATE NOT NULL,
  `DatumZavrsetka` DATE NOT NULL,
  PRIMARY KEY (`KalendarLovaId`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`LOVNI_KALENDAR_DIVLJACI` (
  `DivljacId` INT NOT NULL AUTO_INCREMENT,
  `KalendarLovaId` INT NOT NULL,
  `Brojnost` INT NULL,
  PRIMARY KEY (`DivljacId`, `KalendarLovaId`),
  INDEX `fk_DIVLJAC_has_LOVNI_KALENDAR_LOVNI_KALENDAR1_idx` (`KalendarLovaId` ASC) VISIBLE,
  INDEX `fk_DIVLJAC_has_LOVNI_KALENDAR_DIVLJAC1_idx` (`DivljacId` ASC) VISIBLE,
  CONSTRAINT `fk_DIVLJAC_has_LOVNI_KALENDAR_DIVLJAC1`
    FOREIGN KEY (`DivljacId`)
    REFERENCES `BP_Lovacki_Savez`.`DIVLJAC` (`DivljacId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DIVLJAC_has_LOVNI_KALENDAR_LOVNI_KALENDAR1`
    FOREIGN KEY (`KalendarLovaId`)
    REFERENCES `BP_Lovacki_Savez`.`LOVNI_KALENDAR` (`KalendarLovaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`EVIDENCIJA_ODSTRELA` (
  `EvidencijaOdstrelaId` INT NOT NULL AUTO_INCREMENT,
  `DivljacId` INT NOT NULL,
  `OsobaId` INT NOT NULL,
  `DatumOdstrela` DATE NOT NULL,
  PRIMARY KEY (`EvidencijaOdstrelaId`),
  INDEX `fk_EVIDENCIJA_ODSTRELA_DIVLJAC1_idx` (`DivljacId` ASC) VISIBLE,
  INDEX `fk_EVIDENCIJA_ODSTRELA_CLAN1_idx` (`OsobaId` ASC) VISIBLE,
  CONSTRAINT `fk_EVIDENCIJA_ODSTRELA_DIVLJAC1`
    FOREIGN KEY (`DivljacId`)
    REFERENCES `BP_Lovacki_Savez`.`DIVLJAC` (`DivljacId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EVIDENCIJA_ODSTRELA_CLAN1`
    FOREIGN KEY (`OsobaId`)
    REFERENCES `BP_Lovacki_Savez`.`CLAN` (`OsobaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;





CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`TELEFON_SAVEZA` (
  `BrojTelefona` VARCHAR(20) NOT NULL,
  `LovackiSavezId` INT NOT NULL,
  PRIMARY KEY (`LovackiSavezId`, `BrojTelefona`),
  INDEX `fk_TELEFON_SAVEZA_LOVACKI_SAVEZ1_idx` (`LovackiSavezId` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFON_SAVEZA_LOVACKI_SAVEZ1`
    FOREIGN KEY (`LovackiSavezId`)
    REFERENCES `BP_Lovacki_Savez`.`LOVACKI_SAVEZ` (`LovackiSavezId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`GRUPA` (
  `GrupaId` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `BrojClanovaUGrupi` INT NOT NULL,
  `SekcijaId` INT NOT NULL,
  PRIMARY KEY (`GrupaId`),
  INDEX `fk_GRUPA_SEKCIJA1_idx` (`SekcijaId` ASC) VISIBLE,
  CONSTRAINT `fk_GRUPA_SEKCIJA1`
    FOREIGN KEY (`SekcijaId`)
    REFERENCES `BP_Lovacki_Savez`.`SEKCIJA` (`SekcijaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`LOVACKO_UDRUZENJE_CLANA` (
  `OsobaId` INT NOT NULL,
  `LovackoUdruzenjeId` INT NOT NULL,
  `GrupaId` INT NULL,
  PRIMARY KEY (`OsobaId`, `LovackoUdruzenjeId`),
  INDEX `fk_CLAN_has_LOVACKO_UDRUZENJE_LOVACKO_UDRUZENJE1_idx` (`LovackoUdruzenjeId` ASC) VISIBLE,
  INDEX `fk_CLAN_has_LOVACKO_UDRUZENJE_CLAN1_idx` (`OsobaId` ASC) VISIBLE,
  INDEX `fk_LOVACKO_UDRUZENJE_CLANA_GRUPA1_idx` (`GrupaId` ASC) VISIBLE,
  CONSTRAINT `fk_CLAN_has_LOVACKO_UDRUZENJE_CLAN1`
    FOREIGN KEY (`OsobaId`)
    REFERENCES `BP_Lovacki_Savez`.`CLAN` (`OsobaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CLAN_has_LOVACKO_UDRUZENJE_LOVACKO_UDRUZENJE1`
    FOREIGN KEY (`LovackoUdruzenjeId`)
    REFERENCES `BP_Lovacki_Savez`.`LOVACKO_UDRUZENJE` (`LovackoUdruzenjeId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LOVACKO_UDRUZENJE_CLANA_GRUPA1`
    FOREIGN KEY (`GrupaId`)
    REFERENCES `BP_Lovacki_Savez`.`GRUPA` (`GrupaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `BP_Lovacki_Savez`.`TELEFON_UDRUZENJA` (
  `BrojTelefona` VARCHAR(20) NOT NULL,
  `LovackoUdruzenjeId` INT NOT NULL,
  PRIMARY KEY (`BrojTelefona`, `LovackoUdruzenjeId`),
  INDEX `fk_TELEFON_UDRUZENJA_LOVACKO_UDRUZENJE1_idx` (`LovackoUdruzenjeId` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFON_UDRUZENJA_LOVACKO_UDRUZENJE1`
    FOREIGN KEY (`LovackoUdruzenjeId`)
    REFERENCES `BP_Lovacki_Savez`.`LOVACKO_UDRUZENJE` (`LovackoUdruzenjeId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;